---
title: "FIFA 21 Analysis"
author: "Nathan Weldon"
format: pdf
editor: visual
---

## Introduction

Here, I will load in packages and narrow down what I want to work with for this dataset.

```{r include = FALSE}
library(tidyverse)

data <- fifa21_raw_data %>% 
  select(-c(photoUrl,playerUrl, `Loan Date End`, `Release Clause`))
```

## Cleaning

Checkout the `Team & Contract` column and separate by how long they have their contract period and their club. Then, find which players have played at a club for more than 10 years:

```{r}
#clean
teamtime <- data %>% 
  drop_na() %>% 
  mutate('contract' = str_sub(`Team & Contract`, start = -13)) %>% 
  mutate('team' = str_sub(`Team & Contract`, start = 1, end = -15)) %>% 
  select(-c(`Team & Contract`))

#players 10+ years
a <- str_sub(teamtime$contract, start = -4, end = -3) %>% 
  as.numeric()
b <- str_sub(teamtime$contract, start = 3, end = 4) %>% 
  as.numeric()

decades <- teamtime %>% 
  mutate('Years_at_club'= a-b) %>% 
  filter(c(a-b) >= 10) %>% 
  select(c(Name, Years_at_club))

tibble(decades)
```

Game

```{r}
costs <- data %>% 
  drop_na() %>% 
  mutate('value_millions' = str_extract(Value, "[0-9]+\\.*[0-9]+")) %>% 
  mutate('wage_thousands' = str_extract(Wage, "[0-9]+\\.*[0-9]+")) %>% 
  clean_names() %>% 
  select(75,74,6)
worth <- costs %>% 
  drop_na() %>% 
  tibble(value = as.numeric(value_millions) * 1000000,
          overall = Overall)
worth %>% ggplot(aes(x = overall, y = value_millions)) + geom_point()


```
